In [36]:
import numpy as np

In [2]:
def Gauss_Elim(A,b):
    n = len(b)
    
    for k in range(0, n - 1):
        for i in range(k + 1, n):
            if A[i, k] != 0.0:
                coeff = A[i, k] / A[k, k]
                A[i] -= coeff * A[k]
                b[i] -= coeff * b[k]
                
    for k in range(n - 1, -1, -1):
        b[k] = (b[k] - np.dot(A[k, k + 1:n], b[k + 1:n])) / A[k, k]
    return A, b

In [8]:
A = np.array([[3, 2, 1], [1, -1, 2],[2, 2, 1]], dtype=float)
b = np.array([2, -1, 3], dtype=float)
Gauss_Elim(A, b)

(array([[ 3.        ,  2.        ,  1.        ],
        [ 0.        , -1.66666667,  1.66666667],
        [ 0.        ,  0.        ,  1.        ]]),
 array([-1.,  2.,  1.]))

In [25]:
def Thomas_method(A, b):
    n = len(b)
    alpha = np.hstack((np.zeros(1), A.diagonal(-1)))
    betta = A.diagonal() * -1
    gamma = np.hstack((A.diagonal(1), np.zeros(1)))
    
    P = np.zeros(n)
    Q = np.zeros(n)
    
    for i in range(0, n):
        P[i] = gamma[i] / (betta[i] - alpha[i] * P[i - 1])
        Q[i] = (alpha[i] * Q[i - 1] - b[i]) / (betta[i] - alpha[i] * P[i - 1])
        
    x = np.zeros(n)
    x[n - 1] = Q[n - 1]
    for j in range(n-2, -1, -1):
        x[j] = P[j] * x[j+1] + Q[j]
    return x

In [26]:
A = np.array([[2, 1, 0, 0], [2, 3, -1, -1], [0, 1, -1, 3], [0, 0, 1, -1]])
b = np.array([4, 9, 12, -4])
Thomas_method(A,b)

array([ 1.,  2., -1.,  3.])