In [56]:
import numpy as np
from numpy import zeros, argmax, array
def swap_rows(A, i, j):
    A[[i, j]] = A[[j, i]]
    return A

In [57]:
def LU_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n, n))
    P = np.zeros((n , n))
    
    for i in range(0, n):
        for j in range(0, i):
            L[i, j] = (A[i, j] - np.dot(L[i, 0:j], U[0:j, j])) / U[j, j]
        for j in range(i, n):
            U[i, j] = A[i, j] - np.dot(L[i, 0:i], U[0:i, j])
             
    

    return (L, U)

In [58]:
def LU_Pivot(A, eps = 1.0e-10):
    
    n = len(A)
    perm = array(range(n))
    
    # Сохраним коэф.нормировки в массив
    s = zeros((n), dtype=float)
    for i in range(n):
        s[i] = max(abs(A[i]))
        
    
    for k in range(0, n-1):
        # Меняем строки при необходимости
        p = int(argmax(abs(A[k:n, k])/s[k:n])) + k
        if abs(A[p, k]) < eps:
            print('Матрица вырождена!')
            return np.zeros(n), np.zeros(n)
        if p != k:
            swap_rows(A, k, p)
            swap_rows(s, k, p)
            swap_rows(perm, k, p)
        # Исключение
    
        for i in range(k+1, n):
            if A[i, k] != 0.:
                l_el = A[i,k]/ A[k,k]
                A[i, k+1:n] = A[i, k+1:n] - l_el * A[k, k+1:n]
                A[i,k] = l_el
    
    
    U = np.zeros((n, n), dtype = float)
    L = np.eye(n, n)
    P = np.zeros((n, n), dtype = float)
    
    for i in range(1, n):
        for k in range(0, i):
            L[i, k] += A[i, k]
            
    for i in range(0,n):
        for k in range(i, n):
            U[i, k] += A[i,k]
            
    for i in range(0, n):
        for k in range(0, n):
            if perm[k] == i:
                P[k, i] += 1
                
    return(P, L, U)

In [59]:
A = np.array([[2., -8, 0, 5], [-9, 9, -7, 6], [-6, 7, 3, 8], [-1, 8, 5, 1]])

In [60]:
LU_Pivot(A)

(array([[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.11111111,  1.        ,  0.        ,  0.        ],
        [ 0.66666667,  0.14285714,  1.        ,  0.        ],
        [-0.22222222, -0.85714286,  0.49651972,  1.        ]]),
 array([[-9.        ,  9.        , -7.        ,  6.        ],
        [ 0.        ,  7.        ,  5.77777778,  0.33333333],
        [ 0.        ,  0.        ,  6.84126984,  3.95238095],
        [ 0.        ,  0.        ,  0.        ,  4.65661253]]))